# 张量的数学运算

## 标量运算

In [1]:
import torch
import numpy as np

In [2]:
a = torch.tensor([[1.0, 2], [-3, 4.0]])
b = torch.tensor([[5.0, 6], [7.0, 8.0]])

a + b

tensor([[ 6.,  8.],
        [ 4., 12.]])

In [3]:
a - b

tensor([[ -4.,  -4.],
        [-10.,  -4.]])

In [4]:
a / b

tensor([[ 0.2000,  0.3333],
        [-0.4286,  0.5000]])

In [5]:
a ** 2

tensor([[ 1.,  4.],
        [ 9., 16.]])

In [6]:
a % 3

tensor([[1., 2.],
        [-0., 1.]])

In [7]:
a // 3

tensor([[ 0.,  0.],
        [-1.,  1.]])

In [8]:
a >= 2

tensor([[False,  True],
        [False,  True]])

In [9]:
(a >= 2) & (a <= 3)

tensor([[False,  True],
        [False, False]])

In [10]:
(a >= 2) | (a <= 3)

tensor([[True, True],
        [True, True]])

In [11]:
a == 5

tensor([[False, False],
        [False, False]])

In [12]:
torch.sqrt(a)

tensor([[1.0000, 1.4142],
        [   nan, 2.0000]])

In [13]:
a = torch.tensor([1.0, 8.0])
b = torch.tensor([5.0, 6.0])
c = torch.tensor([6.0, 7.0])

d = a + b + c
print(d)

tensor([12., 21.])


In [14]:
print(torch.max(a, b))

tensor([5., 8.])


In [15]:
print(torch.min(a, b))

tensor([1., 6.])


In [16]:
x = torch.tensor([2.6, -2.7])

print(torch.round(x))
print(torch.floor(x))
print(torch.ceil(x))
print(torch.trunc(x))

tensor([ 3., -3.])
tensor([ 2., -3.])
tensor([ 3., -2.])
tensor([ 2., -2.])


In [17]:
print(torch.fmod(x, 2)) # 做除法取余数
print(torch.remainder(x, 2)) # 作除法取剩余的部分，结果恒正

tensor([ 0.6000, -0.7000])
tensor([0.6000, 1.3000])


In [18]:
x = torch.tensor([0.9, -0.8, 100.0, -20.0, 0.7])
y = torch.clamp(x, min=-1, max = 1)
z = torch.clamp(x, max = 1)
print(y)
print(z)

tensor([ 0.9000, -0.8000,  1.0000, -1.0000,  0.7000])
tensor([  0.9000,  -0.8000,   1.0000, -20.0000,   0.7000])


## 向量运算

In [19]:
a = torch.arange(1, 10).float()
print(torch.sum(a))
print(torch.mean(a))
print(torch.max(a))
print(torch.min(a))
print(torch.prod(a))
print(torch.std(a))
print(torch.var(a))
print(torch.median(a))

tensor(45.)
tensor(5.)
tensor(9.)
tensor(1.)
tensor(362880.)
tensor(2.7386)
tensor(7.5000)
tensor(5.)


In [20]:
b = a.view(3, 3)
print(b)
print(torch.max(b, dim=0))
print(torch.max(b, dim=1))

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
torch.return_types.max(
values=tensor([7., 8., 9.]),
indices=tensor([2, 2, 2]))
torch.return_types.max(
values=tensor([3., 6., 9.]),
indices=tensor([2, 2, 2]))


In [21]:
a = torch.arange(1, 10)

print(torch.cumsum(a, 0))
print(torch.cumprod(a, 0))

tensor([ 1,  3,  6, 10, 15, 21, 28, 36, 45])
tensor([     1,      2,      6,     24,    120,    720,   5040,  40320, 362880])


In [22]:
a = torch.tensor([[9, 7, 8], [1, 3, 2], [5, 6, 4]]).float()
print(torch.topk(a, 2, dim=0), '\n')
print(torch.topk(a, 2, dim=1), '\n')
print(torch.sort(a, dim=1), '\n')

torch.return_types.topk(
values=tensor([[9., 7., 8.],
        [5., 6., 4.]]),
indices=tensor([[0, 0, 0],
        [2, 2, 2]])) 

torch.return_types.topk(
values=tensor([[9., 8.],
        [3., 2.],
        [6., 5.]]),
indices=tensor([[0, 2],
        [1, 2],
        [1, 0]])) 

torch.return_types.sort(
values=tensor([[7., 8., 9.],
        [1., 2., 3.],
        [4., 5., 6.]]),
indices=tensor([[1, 2, 0],
        [0, 2, 1],
        [2, 0, 1]])) 



## 矩阵运算

In [23]:
a = torch.tensor([[1, 2], [3, 4]]).float()
b = torch.tensor([[2, 0], [0, 2]]).float()

print(a@b)

tensor([[2., 4.],
        [6., 8.]])


In [24]:
print(a.T)

tensor([[1., 3.],
        [2., 4.]])


In [25]:
print(torch.inverse(a))

tensor([[-2.0000,  1.0000],
        [ 1.5000, -0.5000]])


In [26]:
print(torch.trace(a))

tensor(5.)


In [27]:
print(torch.norm(a))

tensor(5.4772)


In [28]:
print(torch.det(a))

tensor(-2.0000)


In [29]:
print(torch.eig(a, eigenvectors=True))

torch.return_types.eig(
eigenvalues=tensor([[-0.3723,  0.0000],
        [ 5.3723,  0.0000]]),
eigenvectors=tensor([[-0.8246, -0.4160],
        [ 0.5658, -0.9094]]))


In [30]:
q, r = torch.qr(a)
print(q, "\n")
print(r, "\n")
print(q@r)

tensor([[-0.3162, -0.9487],
        [-0.9487,  0.3162]]) 

tensor([[-3.1623, -4.4272],
        [ 0.0000, -0.6325]]) 

tensor([[1.0000, 2.0000],
        [3.0000, 4.0000]])


In [31]:
a = torch.tensor([[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]])

u, s, v = torch.svd(a)

print(u,"\n")
print(s,"\n")
print(v,"\n")

print(u@torch.diag(s)@v.T)

tensor([[-0.2298,  0.8835],
        [-0.5247,  0.2408],
        [-0.8196, -0.4019]]) 

tensor([9.5255, 0.5143]) 

tensor([[-0.6196, -0.7849],
        [-0.7849,  0.6196]]) 

tensor([[1.0000, 2.0000],
        [3.0000, 4.0000],
        [5.0000, 6.0000]])


## 广播机制

In [32]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([[0, 0, 0], [1, 1, 1], [2, 2, 2]])
print(b + a)

tensor([[1, 2, 3],
        [2, 3, 4],
        [3, 4, 5]])


In [33]:
a_broad, b_broad = torch.broadcast_tensors(a, b)

print(a_broad,"\n")
print(b_broad,"\n")
print(a_broad + b_broad)



tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]) 

tensor([[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]]) 

tensor([[1, 2, 3],
        [2, 3, 4],
        [3, 4, 5]])
