# 张量的结构操作

## 创建张量

In [1]:
import numpy as np
import torch

In [2]:
a = torch.tensor([1, 2, 3], dtype=torch.float)
print(a)

tensor([1., 2., 3.])


In [3]:
b = torch.arange(1, 10, step=2)
print(b)

tensor([1, 3, 5, 7, 9])


In [4]:
c = torch.linspace(0.0, 2 * 3.14, 10)
print(c)

tensor([0.0000, 0.6978, 1.3956, 2.0933, 2.7911, 3.4889, 4.1867, 4.8844, 5.5822,
        6.2800])


In [5]:
d = torch.zeros((3, 3))
print(d)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [6]:
a = torch.ones((3, 3), dtype=torch.int)
b = torch.zeros_like(a, dtype=torch.float)
print(a)
print(b)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [7]:
torch.fill_(b, 5)
print(b)

tensor([[5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]])


In [8]:
torch.manual_seed(0)
minVal, maxVal = 0, 10
a = minVal + (maxVal - minVal) * torch.rand([5])
print(a)

tensor([4.9626, 7.6822, 0.8848, 1.3203, 3.0742])


In [9]:
b = torch.normal(mean=torch.zeros(3, 3), std=torch.ones(3, 3))
print(b)

tensor([[ 0.5507,  0.2704,  0.6472],
        [ 0.2490, -0.3354,  0.4564],
        [-0.6255,  0.4539, -1.3740]])


In [10]:
d = torch.randperm(20)
print(d)

tensor([ 1, 11, 19, 14, 12,  6,  5,  9,  8, 18, 15,  4,  2,  3,  7, 13,  0, 10,
        16, 17])


In [11]:
I = torch.eye(3, 3)
print(I)
t = torch.diag(torch.tensor([1, 2, 3]))
print(t)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([[1, 0, 0],
        [0, 2, 0],
        [0, 0, 3]])


## 索引切片

In [12]:
torch.manual_seed(0)
minVal, maxVal = 0, 10
t = torch.floor(minVal + (maxVal - minVal) * torch.rand([5, 5])).int()
print(t)

tensor([[4, 7, 0, 1, 3],
        [6, 4, 8, 4, 6],
        [3, 4, 0, 1, 2],
        [5, 6, 8, 1, 2],
        [6, 9, 3, 8, 4]], dtype=torch.int32)


In [13]:
print(t[0])

tensor([4, 7, 0, 1, 3], dtype=torch.int32)


In [14]:
print(t[-1])

tensor([6, 9, 3, 8, 4], dtype=torch.int32)


In [15]:
print(t[1, 3])
print(t[1][3])

tensor(4, dtype=torch.int32)
tensor(4, dtype=torch.int32)


In [16]:
print(t[1 : 4, :])

tensor([[6, 4, 8, 4, 6],
        [3, 4, 0, 1, 2],
        [5, 6, 8, 1, 2]], dtype=torch.int32)


In [18]:
print(t[1 : 4, : 4 : 2])

tensor([[6, 8],
        [3, 0],
        [5, 8]], dtype=torch.int32)


In [19]:
x = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32, requires_grad=True)
x.data[1, :] = torch.tensor([0.0, 0.0])
print(x)

tensor([[1., 2.],
        [0., 0.]], requires_grad=True)


In [20]:
a = torch.arange(27).view(3, 3, 3)
print(a)

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]])


In [21]:
print(a[..., 1])

tensor([[ 1,  4,  7],
        [10, 13, 16],
        [19, 22, 25]])


In [22]:
# 4个班级，每个班级10个学生，每个学生7门科目成绩

minVal, maxVal = 0, 100
scores = torch.floor(minVal + (maxVal - minVal) * torch.rand([4, 10, 7]))
print(scores)

tensor([[[55., 95.,  3., 18., 37., 30., 93.],
         [17., 26., 15.,  3., 20., 92., 72.],
         [74., 52., 24., 58.,  3., 13., 24.],
         [81., 79., 27., 48., 81., 99., 69.],
         [56., 83., 20., 59., 11., 15., 24.],
         [72., 70., 20., 65., 77., 43., 51.],
         [61., 81., 98., 11., 31., 69., 91.],
         [93., 94., 59.,  6., 54., 18.,  3.],
         [94., 88.,  0., 59., 41., 41., 27.],
         [69., 20., 68., 75., 85., 68.,  0.]],

        [[17., 74., 60., 10., 21., 97., 83.],
         [28., 37.,  2., 49., 12., 11., 47.],
         [57., 29., 79., 19., 95., 84.,  7.],
         [37., 52., 57., 61., 69., 52., 25.],
         [73.,  2., 20., 37., 25., 32.,  9.],
         [39., 60., 17., 47., 85., 44., 51.],
         [45., 60., 81., 97., 81., 97., 46.],
         [ 5., 26., 84., 49., 25., 11.,  3.],
         [ 7., 39., 77., 77.,  1., 81., 10.],
         [39., 29., 40., 40.,  5.,  6., 42.]],

        [[50., 27., 68.,  4., 46., 93., 29.],
         [95., 68.,  4., 81., 

In [23]:
# 抽取每个班级第0个学生，第5个学生，第9个学生的全部成绩

torch.index_select(scores, dim=1, index=torch.tensor([0, 5, 9]))

tensor([[[55., 95.,  3., 18., 37., 30., 93.],
         [72., 70., 20., 65., 77., 43., 51.],
         [69., 20., 68., 75., 85., 68.,  0.]],

        [[17., 74., 60., 10., 21., 97., 83.],
         [39., 60., 17., 47., 85., 44., 51.],
         [39., 29., 40., 40.,  5.,  6., 42.]],

        [[50., 27., 68.,  4., 46., 93., 29.],
         [52., 82., 12., 15., 20., 84., 32.],
         [33., 42., 50., 91., 56., 94., 80.]],

        [[18., 72., 14., 28., 64., 66., 87.],
         [26., 26.,  2., 60., 21.,  5., 93.],
         [70., 33., 25., 58., 24., 61., 59.]]])

In [24]:
# 抽取每个班级第0个学生，第5个学生，第9个学生的第1门课程，第3门课程，第6门课程成绩

q = torch.index_select(torch.index_select(scores, dim=1, index=torch.tensor([0, 5, 9])), dim=2, index=torch.tensor([1, 3, 6]))
print(q)

tensor([[[95., 18., 93.],
         [70., 65., 51.],
         [20., 75.,  0.]],

        [[74., 10., 83.],
         [60., 47., 51.],
         [29., 40., 42.]],

        [[27.,  4., 29.],
         [82., 15., 32.],
         [42., 91., 80.]],

        [[72., 28., 87.],
         [26., 60., 93.],
         [33., 58., 59.]]])


In [25]:
# 抽取第0个班级第0个学生的第0门课程，第2个班级的第4个学生的第1门课程，第3个班级的第9个学生第6门课程成绩

s = torch.take(scores, torch.tensor([0 * 10 * 7 + 0, 2 * 10 * 7 + 4 * 7 + 1, 3 * 10 * 7 + 9 * 7 + 6]))
print(s)

tensor([55., 14., 59.])


In [26]:
# 抽取分数大于等于80分的分数（布尔索引
g = torch.masked_select(scores, scores >= 80)
print(g)

tensor([95., 93., 92., 81., 81., 99., 83., 81., 98., 91., 93., 94., 94., 88.,
        85., 97., 83., 95., 84., 85., 81., 97., 81., 97., 84., 81., 93., 95.,
        81., 89., 85., 89., 84., 82., 84., 92., 90., 99., 91., 94., 80., 87.,
        86., 91., 88., 91., 93., 89., 91., 84.])


In [27]:
# 如果分数大于60分，赋值成1，否则赋值成0
ispass = torch.where(scores >= 60, torch.tensor(1), torch.tensor(0))
print(ispass)

tensor([[[0, 1, 0, 0, 0, 0, 1],
         [0, 0, 0, 0, 0, 1, 1],
         [1, 0, 0, 0, 0, 0, 0],
         [1, 1, 0, 0, 1, 1, 1],
         [0, 1, 0, 0, 0, 0, 0],
         [1, 1, 0, 1, 1, 0, 0],
         [1, 1, 1, 0, 0, 1, 1],
         [1, 1, 0, 0, 0, 0, 0],
         [1, 1, 0, 0, 0, 0, 0],
         [1, 0, 1, 1, 1, 1, 0]],

        [[0, 1, 1, 0, 0, 1, 1],
         [0, 0, 0, 0, 0, 0, 0],
         [0, 0, 1, 0, 1, 1, 0],
         [0, 0, 0, 1, 1, 0, 0],
         [1, 0, 0, 0, 0, 0, 0],
         [0, 1, 0, 0, 1, 0, 0],
         [0, 1, 1, 1, 1, 1, 0],
         [0, 0, 1, 0, 0, 0, 0],
         [0, 0, 1, 1, 0, 1, 0],
         [0, 0, 0, 0, 0, 0, 0]],

        [[0, 0, 1, 0, 0, 1, 0],
         [1, 1, 0, 1, 0, 0, 1],
         [0, 0, 0, 1, 1, 1, 1],
         [0, 0, 0, 1, 1, 1, 0],
         [0, 0, 0, 0, 1, 0, 0],
         [0, 1, 0, 0, 0, 1, 0],
         [1, 1, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 1, 0, 0],
         [1, 1, 0, 0, 1, 0, 0],
         [0, 0, 0, 1, 0, 1, 1]],

        [[0, 1, 0, 0, 1, 1, 1],
  

In [28]:
# 将每个班级第0个学生，第5个学生，第9个学生的全部成绩赋值成满分
torch.index_fill(scores, dim=1, index=torch.tensor([0, 5, 9]), value=100)

tensor([[[100., 100., 100., 100., 100., 100., 100.],
         [ 17.,  26.,  15.,   3.,  20.,  92.,  72.],
         [ 74.,  52.,  24.,  58.,   3.,  13.,  24.],
         [ 81.,  79.,  27.,  48.,  81.,  99.,  69.],
         [ 56.,  83.,  20.,  59.,  11.,  15.,  24.],
         [100., 100., 100., 100., 100., 100., 100.],
         [ 61.,  81.,  98.,  11.,  31.,  69.,  91.],
         [ 93.,  94.,  59.,   6.,  54.,  18.,   3.],
         [ 94.,  88.,   0.,  59.,  41.,  41.,  27.],
         [100., 100., 100., 100., 100., 100., 100.]],

        [[100., 100., 100., 100., 100., 100., 100.],
         [ 28.,  37.,   2.,  49.,  12.,  11.,  47.],
         [ 57.,  29.,  79.,  19.,  95.,  84.,   7.],
         [ 37.,  52.,  57.,  61.,  69.,  52.,  25.],
         [ 73.,   2.,  20.,  37.,  25.,  32.,   9.],
         [100., 100., 100., 100., 100., 100., 100.],
         [ 45.,  60.,  81.,  97.,  81.,  97.,  46.],
         [  5.,  26.,  84.,  49.,  25.,  11.,   3.],
         [  7.,  39.,  77.,  77.,   1.,  81.

In [29]:
#将分数小于60分的分数赋值成60分
# 等价于b = scores.masked_fill(scores < 60, 60)

b = torch.masked_fill(scores, scores < 60, 60)

print(b)

tensor([[[60., 95., 60., 60., 60., 60., 93.],
         [60., 60., 60., 60., 60., 92., 72.],
         [74., 60., 60., 60., 60., 60., 60.],
         [81., 79., 60., 60., 81., 99., 69.],
         [60., 83., 60., 60., 60., 60., 60.],
         [72., 70., 60., 65., 77., 60., 60.],
         [61., 81., 98., 60., 60., 69., 91.],
         [93., 94., 60., 60., 60., 60., 60.],
         [94., 88., 60., 60., 60., 60., 60.],
         [69., 60., 68., 75., 85., 68., 60.]],

        [[60., 74., 60., 60., 60., 97., 83.],
         [60., 60., 60., 60., 60., 60., 60.],
         [60., 60., 79., 60., 95., 84., 60.],
         [60., 60., 60., 61., 69., 60., 60.],
         [73., 60., 60., 60., 60., 60., 60.],
         [60., 60., 60., 60., 85., 60., 60.],
         [60., 60., 81., 97., 81., 97., 60.],
         [60., 60., 84., 60., 60., 60., 60.],
         [60., 60., 77., 77., 60., 81., 60.],
         [60., 60., 60., 60., 60., 60., 60.]],

        [[60., 60., 68., 60., 60., 93., 60.],
         [95., 68., 60., 81., 

## 维度变换

In [30]:
torch.manual_seed(0)
minVal, maxVal = 0, 255
a = (minVal + (maxVal - minVal) * torch.rand([1, 3, 3, 2])).int()
print(a.shape)
print(a)

torch.Size([1, 3, 3, 2])
tensor([[[[126, 195],
          [ 22,  33],
          [ 78, 161]],

         [[124, 228],
          [116, 161],
          [ 88, 102]],

         [[  5,  43],
          [ 74, 132],
          [177, 204]]]], dtype=torch.int32)


In [32]:
b = a.view([3, 6])
print(b)

tensor([[126, 195,  22,  33,  78, 161],
        [124, 228, 116, 161,  88, 102],
        [  5,  43,  74, 132, 177, 204]], dtype=torch.int32)


In [33]:
c = torch.reshape(b, [1, 3, 3, 2])
print(c)

tensor([[[[126, 195],
          [ 22,  33],
          [ 78, 161]],

         [[124, 228],
          [116, 161],
          [ 88, 102]],

         [[  5,  43],
          [ 74, 132],
          [177, 204]]]], dtype=torch.int32)


In [34]:
a = torch.tensor([[1.0, 2.0]])
s = torch.squeeze(a)
print(a)
print(s)
print(a.shape)
print(s.shape)

tensor([[1., 2.]])
tensor([1., 2.])
torch.Size([1, 2])
torch.Size([2])


In [35]:
d = torch.unsqueeze(s, axis=0)
print(s)
print(d)

print(s.shape)
print(d.shape)

tensor([1., 2.])
tensor([[1., 2.]])
torch.Size([2])
torch.Size([1, 2])


In [36]:
minVal , maxVal= 0, 255
# Batch,Height,Width,Channel
data = torch.floor(minVal + (maxVal - minVal) * torch.rand([100, 256, 256, 4])).int()
print(data.shape)

# 转换成 Pytorch默认的图片格式 Batch,Channel,Height,Width
# 需要交换两次
data_t = torch.transpose(torch.transpose(data,1,2),1,3)
print(data_t.shape)

torch.Size([100, 256, 256, 4])
torch.Size([100, 4, 256, 256])


In [37]:
matrix = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(matrix)
print(matrix.t())

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])


## 合并分割

In [42]:
a = torch.tensor([[1.0, 2.0], [3.0, 4.0]])
b = torch.tensor([[5.0, 6.0], [7.0, 8.0]])
c = torch.tensor([[9.0, 10.0], [11.0, 12.0]])

abc_cat = torch.cat([a, b, c], dim=0)
print(abc_cat.shape)
print(abc_cat)

torch.Size([6, 2])
tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.],
        [11., 12.]])


In [43]:
abc_stack = torch.stack([a, b, c], dim=0)
print(abc_stack.shape)
print(abc_stack)

torch.Size([3, 2, 2])
tensor([[[ 1.,  2.],
         [ 3.,  4.]],

        [[ 5.,  6.],
         [ 7.,  8.]],

        [[ 9., 10.],
         [11., 12.]]])


In [44]:
torch.cat([a, b, c], axis=1)

tensor([[ 1.,  2.,  5.,  6.,  9., 10.],
        [ 3.,  4.,  7.,  8., 11., 12.]])

In [45]:
torch.stack([a, b, c], axis=1)

tensor([[[ 1.,  2.],
         [ 5.,  6.],
         [ 9., 10.]],

        [[ 3.,  4.],
         [ 7.,  8.],
         [11., 12.]]])

In [46]:
print(abc_cat)
a, b, c = torch.split(abc_cat, split_size_or_sections=2, dim=0) #每份2个进行分割
print(a)
print(b)
print(c)

tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.],
        [11., 12.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[5., 6.],
        [7., 8.]])
tensor([[ 9., 10.],
        [11., 12.]])


In [47]:
print(abc_cat)
p, q, r = torch.split(abc_cat, split_size_or_sections=[4, 1, 1], dim=0) #每份分别为[4,1,1]
print(p)
print(q)
print(r)


tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.],
        [11., 12.]])
tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[ 9., 10.]])
tensor([[11., 12.]])
