# 张量数据结构

## 张量数据类型

* torch.float64(torch.double)
* torch.float32(torch.float)
* torch.float16
* torch.int64(torch.long)
* torch.int32(torch.int)
* torch.int16
* torch.int8
* torch.uint8
* torch.bool

一般神经网络建模使用的都是torch.float32类型。

In [1]:
import torch

i = torch.tensor(1);print(i, i.dtype)
x = torch.tensor(2.0);print(x, x.dtype)
b = torch.tensor(True);print(b, b.dtype)

tensor(1) torch.int64
tensor(2.) torch.float32
tensor(True) torch.bool


In [2]:
# 使用特定类型构造函数
import numpy as np

i = torch.IntTensor(1);print(i,i.dtype)
x = torch.Tensor(np.array(2.0));print(x,x.dtype) #等价于torch.FloatTensor
b = torch.BoolTensor(np.array([1,0,2,0])); print(b,b.dtype)

tensor([0], dtype=torch.int32) torch.int32
tensor(2.) torch.float32
tensor([ True, False,  True, False]) torch.bool


In [3]:
i = torch.tensor(1);print(i, i.dtype)
x = i.float(); print(x, x.dtype) # 调用 float方法转换成浮点类型
y = i.type(torch.float);print(y, y.dtype) #使用type函数转换成浮点类型
z = i.type_as(x);print(z, z.dtype) # 使用type_as方法转换成某个Tensor相同类型

tensor(1) torch.int64
tensor(1.) torch.float32
tensor(1.) torch.float32
tensor(1.) torch.float32


## 张量的维度

不同类型的数据可以用不同维度(dimension)的张量来表示。标量为0维张量，向量为1维张量，矩阵为2维张量。彩色图像有rgb三个通道，可以表示为3维张量。视频还有时间维，可以表示为4维张量。

In [4]:
scalar = torch.tensor(True)
print(scalar)
print(scalar.dim())

tensor(True)
0


In [5]:
vector = torch.tensor([1.0, 2.0, 3.0])
print(vector)
print(vector.dim())

tensor([1., 2., 3.])
1


In [6]:
matrix = torch.tensor([[1.0, 2.0], [3.0, 4.0]])
print(matrix)
print(matrix.dim())

tensor([[1., 2.],
        [3., 4.]])
2


In [7]:
img = torch.tensor([[[1.0, 2.0],[3.0, 4.0]],[[5.0, 6.0],[7.0, 8.0]]])
print(img)
print(img.dim())

tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])
3


In [8]:
video = torch.tensor([[[[1.0, 1.0],[2.0, 2.0]],[[3.0, 3.0],[4.0, 4.0]]],
                        [[[5.0, 5.0],[6.0, 6.0]],[[7.0, 7.0],[8.0, 8.0]]]])
print(video)
print(video.dim())

tensor([[[[1., 1.],
          [2., 2.]],

         [[3., 3.],
          [4., 4.]]],


        [[[5., 5.],
          [6., 6.]],

         [[7., 7.],
          [8., 8.]]]])
4


## 张量的尺寸

In [10]:
matrix.shape

torch.Size([2, 2])

In [11]:
img.shape

torch.Size([2, 2, 2])

In [12]:
img.view((4, 2))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])

In [13]:
img.reshape((4, 2))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])

## 张量和numpy数组

In [14]:
import numpy as np
import torch

In [15]:
arr = np.zeros(3)
tensor = torch.from_numpy(arr)
print("before add 1:")
print(arr)
print(tensor)

print("\nafter add 1:")
np.add(arr,1, out = arr)
print(arr)
print(tensor)

before add 1:
[0. 0. 0.]
tensor([0., 0., 0.], dtype=torch.float64)

after add 1:
[1. 1. 1.]
tensor([1., 1., 1.], dtype=torch.float64)


In [16]:
tensor = torch.zeros(3)
arr = tensor.numpy()
print("before add 1:")
print(tensor)
print(arr)

print("\nafter add 1:")

#使用带下划线的方法表示计算结果会返回给调用 张量
tensor.add_(1) #给 tensor增加1，arr也随之改变
#或： torch.add(tensor,1,out = tensor)
print(tensor)
print(arr)

before add 1:
tensor([0., 0., 0.])
[0. 0. 0.]

after add 1:
tensor([1., 1., 1.])
[1. 1. 1.]


In [17]:
# 可以用clone() 方法拷贝张量，中断这种关联

tensor = torch.zeros(3)

#使用clone方法拷贝张量, 拷贝后的张量和原始张量内存独立
arr = tensor.clone().numpy() # 也可以使用tensor.data.numpy()
print("before add 1:")
print(tensor)
print(arr)

print("\nafter add 1:")

#使用 带下划线的方法表示计算结果会返回给调用 张量
tensor.add_(1) #给 tensor增加1，arr不再随之改变
print(tensor)
print(arr)

before add 1:
tensor([0., 0., 0.])
[0. 0. 0.]

after add 1:
tensor([1., 1., 1.])
[0. 0. 0.]


In [18]:
# item方法和tolist方法可以将张量转换成Python数值和数值列表
scalar = torch.tensor(1.0)
s = scalar.item()
print(s)
print(type(s))

tensor = torch.rand(2,2)
t = tensor.tolist()
print(t)
print(type(t))

1.0
<class 'float'>
[[0.344498872756958, 0.04645782709121704], [0.31299924850463867, 0.28313326835632324]]
<class 'list'>
